# -*- coding: utf-8 -*-
"""Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10e-zWccVdVhzR0dACmzpjyuyQqrBaXsn

# Importação de Bibliotecas
"""

# Manipulação de dados
import pandas as pd
import numpy as np

# Visualização
import matplotlib.pyplot as plt
import seaborn as sns

"""# Carregamento e Vizualização de Dados

## Leitura
"""

df = pd.read_excel("/content/Superstore.xlsx", dtype=str, keep_default_na=False, na_values=["", "NA", "N/A", "null"])

"""## Vizualizar primeiras linhas"""

df.head(10)

"""## Informarções gerais da tabela"""

df.info()

"""## Contagem de valores nulos"""

df.isna().sum().sort_values(ascending=False)

"""## Contagem valores unicos por coluna"""

df.nunique().sort_values(ascending=False)

"""# Limpeza dos Dados (Data Cleaning)

## Convertendo Para Datas
"""

df["Data do Pedido"] = pd.to_datetime(df["Data do Pedido"])
df["Data do Envio"] = pd.to_datetime(df["Data do Envio"])

"""## Convertendo Para Numericos"""

numericos = ["Valor venda", "Quantidade", "Desconto", "Lucro"]

for col in cols_numericas:
    df[col] = df[col].astype(float)

"""## Verificação valores faltantes"""

df.replace(["", " ", "NA", "N/A", "null", "-"], np.nan, inplace=True)
df.isna().sum()

"""## Criando Coluna Ano, Mes e Dia"""

df["Ano"] = df["Data do Pedido"].dt.year
df["Mes"] = df["Data do Pedido"].dt.month
df["Dia"] = df["Data do Pedido"].dt.day
df["Envio Dias"] = (df["Data do Envio"] - df["Data do Pedido"]).dt.days

"""## Criando a coluna "Valor Unitário"
"""

df['Valor Unitario'] = df['Valor venda'] / df['Quantidade']

# Conferindo as primeiras linhas
df[['Valor venda', 'Quantidade', 'Valor Unitario']].head()

"""## Criando Margem %"""

df['Margem'] = df['Lucro'] / df['Valor venda']

"""## Lista de colunas para manter apenas 2 casas decimais"""

colunas_duas_casas = ['Valor venda', 'Lucro', 'Valor Unitario', 'Margem']

# Arredondar para 2 casas decimais
df[colunas_duas_casas] = df[colunas_duas_casas].round(2)

# Converter desconto para porcentagem (ex: 0.45 → 45.00)
df['Desconto'] = (df['Desconto'] * 100).round(2)

"""## Remoção duplicada"""

df.drop_duplicates(inplace=True)

"""## Detectar ouliers"""

df[["Valor venda", "Lucro"]].describe()

"""## Vizualização"""

df.head(10)

"""# Análise Exploratória dos Dados (EDA)

## Histogramas
"""

for col in numericos:
    plt.figure(figsize=(8,4))
    plt.hist(df[col], bins=30)
    plt.title(f"Distribuição de {col}")
    plt.xlabel(col)
    plt.ylabel("Frequência")
    plt.show()

"""## Boxplot"""

for col in numericos:
    plt.figure(figsize=(8,3))
    sns.boxplot(x=df[col])
    plt.title(f"Boxplot de {col}")
    plt.xlabel(col)
    plt.show()

"""## Matriz de Correlação"""

plt.figure(figsize=(8,6))
sns.heatmap(df[numericos].corr(), annot=True, cmap="Blues")
plt.title("Correlação entre variáveis numéricas")
plt.show()

"""## Y em Função de X"""

pairs = [
    ("Valor venda", "Lucro"),
    ("Quantidade", "Valor venda"),
    ("Desconto", "Lucro")
]

for x, y in pairs:
    plt.figure(figsize=(7,5))
    sns.scatterplot(data=df, x=x, y=y)
    plt.title(f"{y} em função de {x}")
    plt.show()

"""## Media valores por categoria"""

agrupamentos = [
    "Categoria",
    "Sub-Categoria",
    "Segmento",
    "Estado",
    "Cidade",
    "Região",
    "Nome do Vendedor"
]

for col in agrupamentos:
    print(f"\n#### {col.upper()} ####")
    display(df.groupby(col)[["Valor venda", "Lucro", "Quantidade"]].mean().sort_values("Valor venda", ascending=False))

"""## Total Venda Por Categoria"""

plt.figure(figsize=(8,4))
df.groupby("Categoria")["Valor venda"].sum().sort_values().plot(kind="bar")
plt.title("Total de Vendas por Categoria")
plt.ylabel("Valor de venda")
plt.xlabel("Categoria")
plt.show()

"""## Lucro por estado"""

plt.figure(figsize=(10,4))
df.groupby("Estado")["Lucro"].sum().sort_values().plot(kind="bar")
plt.title("Lucro Total por Estado")
plt.ylabel("Lucro")
plt.xlabel("Estado")
plt.xticks(rotation=90)
plt.show()

"""## Lucros por categoria"""

lucro_categoria = df.groupby('Categoria')['Lucro'].sum().reset_index()

# Plotando o gráfico de barras
plt.figure(figsize=(8,5))
plt.bar(lucro_categoria['Categoria'], lucro_categoria['Lucro'])
plt.title('Lucro por Categoria')
plt.xlabel('Categoria')
plt.ylabel('Lucro Total')
plt.xticks(rotation=45)
plt.show()

"""## Lucros por Sub-Categoria"""

lucro_categoria = df.groupby('Sub-Categoria')['Lucro'].sum().reset_index()

# Plotando o gráfico de barras
plt.figure(figsize=(8,5))
plt.bar(lucro_categoria['Sub-Categoria'], lucro_categoria['Lucro'])
plt.title('Lucro por Categoria')
plt.xlabel('Categoria')
plt.ylabel('Lucro Total')
plt.xticks(rotation=45)
plt.show()

"""## Quantidade vendida por segmento"""

plt.figure(figsize=(7,4))
df.groupby("Segmento")["Quantidade"].sum().plot(kind="bar")
plt.title("Quantidade vendida por Segmento")
plt.ylabel("Quantidade")
plt.xlabel("Segmento")
plt.show()

"""## Passando Ponto Para Virgula"""

cols = ['Valor venda', 'Lucro', 'Valor Unitario', 'Quantidade', 'Desconto', 'Margem']

for col in cols:
    df[col] = df[col].astype(float).round(2)              # garante número com 2 casas
    df[col] = df[col].astype(str).str.replace('.', ',', regex=False)  # troca ponto por vírgula

df.info()

df.head()

"""## Exportando DataSet"""

df.to_csv("superstore_limpo.csv", index=False, sep=';', encoding='utf-8')